name: Java CI with Maven

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ opened, synchronize, reopened ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: |
        cd restful-web-services
        mvn -B package --file pom.xml
    
    - name: Cache SonarQube package
      uses: action/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
        
   
