# This is a basic workflow to help you get started with Actions

name: SonarScan

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        
      - name: Analyse with SonarCLoud
        uses: sonarsource/sonarcloud-github-action@v1.3
        with:
          projectBaseDir: ../octalog/restful-web-services/
          args: >
            - Dsonar.organization = batshal1
            - Dsonar.projectKey = batshal1_octalog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
    

 
